simulation:

  target_load: 0.7
  iterations: 5
  duration: 1000
  bandwidth: 300
  servers:
    - name: Edge server
      operations: 1000
      delay: 3

    - name: Cloud server
      operations: 3000
      delay: 7

  generated_tasks:
    data_size: [ 10, 75 ]
    time_budget: [ 50, 500 ]
    required_computation: [ 50, 500 ]
    privacy_level: [ 1, 10 ]
    