simulation:

  target_load: 39
  iterations: 1
  duration: 500
  bandwidth: 500
  servers:
    - name: Edge server
      operations: 1000
      delay: 5

    - name: Cloud server
      operations: 10000
      delay: 15

  generated_tasks:
    data_size: [ 10, 150 ]
    time_budget: [ 30, 150 ]
    required_computation: [ 30, 250 ]
    privacy_level: [ 1, 10 ]
    